### PR TITLE
Add simple CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by doug-wade**
per gitter discussion

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I think GitHub lets you require a certain number of approvals before the merge button is enabled, right? Can you check if you can set that up for one approval each?

**Comment by doug-wade** [comment]
@nickmccurdy I don't seem to have permissions to [access the setting panel](https://help.github.com/articles/enabling-required-reviews-for-pull-requests/)

**Comment by nickmccurdy** [comment]
Me neither, should we mention someone with access?

**Comment by doug-wade** [comment]
@jonathanong I think we're missing some perms -- would you be willing to grant them?

**Comment by nickmccurdy** [comment]
Feel free if to merge this before we change the settings, unless you want to wait.

**Pull request merged**
